backend:
  name: git-gateway
  branch: main  # Change to your default branch if needed

media_folder: "images/uploads"  # Where images are stored
public_folder: "/images/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
